name: aliyun_oss
description: 'aliyun oss plugin for dart. Use this plugin to upload files to aliyun oss.'
version: 0.0.1
homepage: https://www.kjxbyz.com/flutterfleet
repository: https://github.com/FlutterFleet/FlutterFleet/tree/main/packages/flutter_aliyun_oss

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  path: ^1.9.0
  http_parser: ^4.0.2
  crypto: ^3.0.3
  intl: ^0.19.0
  dio: ^5.5.0+1
  uuid: ^4.4.2

dev_dependencies:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
